import http.server
import socketserver
from urllib.parse import urlparse
from urllib.parse import parse_qs
from urllib import parse

from io import BytesIO

import json


class SimpleHTTPRequestHandler(http.server.SimpleHTTPRequestHandler):

    def do_GET(self):
            # Sending an '200 OK' response
        self.send_response(200)

        # Setting the header
        #self.send_header("Content-type", "text/html")

        # Whenever using 'send_header', you also have to call 'end_headers'
        #self.end_headers()

        # Extract query param
        # global name 
        # query_components = parse_qs(urlparse(self.path))
        # print('query_components', query_components)
        # if 'name' in query_components:
        #     name = query_components["name"][0]
        parse_res=parse.urlparse(self.path)
        print('parse_res', parse_res.path[1:])

        # tacoshop = 
        if self.path == '/tacoshop':
            self.path = './public'+ self.path + '.html'
        else:
            self.path = './public'+ self.path

        print(self.path)

        # self.path = './public/'+'.html'
        
        
        # # Some custom HTML code, possibly generated by another function
        # html = f"<html><head></head><body><h1>Hello {name}!</h1></body></html>"

        # # Writing the HTML contents with UTF-8
        # self.wfile.write(bytes(html, "utf8"))

        #return
        return http.server.SimpleHTTPRequestHandler.do_GET(self)

       

    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length)
        self.send_response(200)
        self.end_headers()

        data = json.loads(body)
        print(data)

        response = BytesIO()
        response.write(b'This is POST request. ')
        response.write(b'Received: ')
        response.write(body)
        self.wfile.write(response.getvalue())

        

httpd = http.server.HTTPServer(('localhost', 8000), SimpleHTTPRequestHandler)
httpd.serve_forever()